name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 730649731642.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: devops-task4-app
  IMAGE_TAG: latest

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t devops-task4-app:${{ env.IMAGE_TAG }} .

      - name: Tag Docker Image
        run: |
          docker tag devops-task4-app:${{ env.IMAGE_TAG }} \
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Push Docker Image
        run: |
          docker push \
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
